"""Starter ``soleaux.toml`` rendering, shared by ``generate soleaux-toml`` and ``attach``."""

from __future__ import annotations

import json as json_mod
import pathlib
import tomllib


def render_soleaux_toml(root: pathlib.Path) -> str:
    """Render a soleaux.toml template from existing workspace configs."""
    lines: list[str] = [
        "# Generated by soleaux from existing workspace configuration.",
        "# Edit and place at the workspace root.",
        "",
    ]

    mcp_json_path = root / ".mcp.json"
    if mcp_json_path.is_file():
        try:
            mcp_data = json_mod.loads(mcp_json_path.read_text(encoding="utf-8"))
            servers = sorted(mcp_data.get("mcpServers", {}).keys())
            if servers:
                lines.append("# [mcp.<name>] entries derived from .mcp.json")
                lines.append("# Enable one per backend as needed:")
                lines.append(f"# servers found: {', '.join(servers)}")
                lines.append("")
        except json_mod.JSONDecodeError:
            pass

    codex_path = root / ".codex" / "config.toml"
    if codex_path.is_file():
        try:
            tomldata = tomllib.loads(codex_path.read_text(encoding="utf-8"))
            for name, cfg in tomldata.get("mcp_servers", {}).items():
                if cfg.get("enabled", True) and "command" in cfg:
                    cmd = cfg["command"]
                    lines.append(f'[mcp."{name}"]')
                    lines.append(f"command = {json_mod.dumps(cmd)}")
                    lines.append('lifecycle = "session"')
                    lines.append("")
        except tomllib.TOMLDecodeError:
            pass

    lines.append("[health]")
    lines.append("logs_retention_days = 7")
    lines.append("temp_retention_hours = 24")
    lines.append("archived_sessions_retention_days = 14")
    lines.append("max_logs_db_size_mb = 500")
    lines.append("")

    from soleaux.suggestions import scan_for_suggestions

    configured_names: set[str] = set()
    for line in lines:
        if line.startswith('[mcp."') or line.startswith("[mcp."):
            name = line.split('"')[1] if '"' in line else line.split("[mcp.")[1].rstrip("]")
            configured_names.add(name)
    suggestions = scan_for_suggestions(root)
    unconfigured = [s for s in suggestions if s.name not in configured_names]
    if unconfigured:
        lines.append("# Suggested MCP servers detected in this workspace:")
        for s in unconfigured:
            lines.append(f"# {s.name}: {s.rationale}")
            if s.command:
                lines.append(f'# [mcp."{s.name}"]')
                lines.append(f"# command = {json_mod.dumps(s.command)}")
                lines.append('# lifecycle = "session"')
            elif s.url:
                lines.append(f'# [mcp."{s.name}"]')
                lines.append(f'# url = "{s.url}"')
                if s.auth_token_env_hint:
                    lines.append(f'# auth_token_env = "{s.auth_token_env_hint}"')
            lines.append("#")
        lines.append("")

    return "\n".join(lines)
