[package]
name = "soleaux-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "soleaux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
soleaux-mcp = { path = "../../daemon/mcp" }
tokio.workspace = true
