[package]
name = "soleaux-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
libc = "0.2.189"
serde.workspace = true
serde_json.workspace = true
soleaux-state = { path = "../state" }
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
