[package]
name = "soleaux-ipc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
blake3.workspace = true
rustix = { version = "1.1.4", features = ["process"] }
serde.workspace = true
serde_json.workspace = true
soleaux-state = { path = "../state" }
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
